# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic
import webbrowser
import datetime


class Ui_Calcul(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.resize(630, 477)
        self.label = QtWidgets.QLabel(self)
        self.difficult = ''
        self.radioButton = QtWidgets.QRadioButton(self)
        self.radioButton_2 = QtWidgets.QRadioButton(self)
        self.radioButton_3 = QtWidgets.QRadioButton(self)
        self.label_2 = QtWidgets.QLabel(self)
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit_2 = QtWidgets.QLineEdit(self)
        self.label_3 = QtWidgets.QLabel(self)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton_3 = QtWidgets.QPushButton(self)
        self.pushButton_4 = QtWidgets.QPushButton(self)
        self.calendarWidget = QtWidgets.QCalendarWidget(self)
        self.pushButton_5 = QtWidgets.QPushButton(self)
        self.label_4 = QtWidgets.QLabel(self)
        self.Messege = QtWidgets.QMessageBox()
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self)
        self.textBrowser = QtWidgets.QLineEdit(self)
        self.setupUi()

    def setupUi(self):
        self.label.setGeometry(QtCore.QRect(10, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.radioButton.setGeometry(QtCore.QRect(210, 80, 95, 20))
        self.radioButton_2.setGeometry(QtCore.QRect(300, 80, 95, 20))
        self.radioButton_3.setGeometry(QtCore.QRect(400, 80, 95, 20))
        self.label_2.setGeometry(QtCore.QRect(10, 70, 181, 41))
        self.lineEdit.setGeometry(QtCore.QRect(10, 140, 113, 22))
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 180, 113, 22))
        self.label_3.setGeometry(QtCore.QRect(10, 110, 131, 16))
        self.pushButton.setGeometry(QtCore.QRect(170, 140, 41, 21))
        self.pushButton_2.setGeometry(QtCore.QRect(170, 180, 41, 21))
        self.pushButton_3.setGeometry(QtCore.QRect(230, 140, 41, 21))
        self.pushButton_4.setGeometry(QtCore.QRect(230, 180, 41, 21))
        self.calendarWidget.setGeometry(QtCore.QRect(10, 230, 392, 236))
        self.pushButton_5.setGeometry(QtCore.QRect(460, 390, 121, 71))
        self.label_4.setGeometry(QtCore.QRect(330, 150, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.commandLinkButton.setGeometry(QtCore.QRect(450, 320, 161, 48))
        self.textBrowser.setGeometry(QtCore.QRect(210, 20, 256, 31))
        self.label.setText("Введите Ваше имя")
        self.radioButton.setText("Легко")
        self.radioButton_2.setText("Средне")
        self.radioButton_3.setText("Сложно")
        self.label_2.setText("Выберите уровень сложности")
        self.label_3.setText("Введите числа")
        self.pushButton.setText("+")
        self.pushButton_2.setText("-")
        self.pushButton_3.setText("*")
        self.pushButton_4.setText("/")
        self.pushButton_5.setText("Отправить")
        self.label_4.setText("Ответ")
        self.commandLinkButton.setText("Примеры")
        self.radioButton_2.clicked.connect(self.OnClicked)
        self.radioButton.clicked.connect(self.OnClicked)
        self.radioButton_3.clicked.connect(self.OnClicked)
        self.pushButton.clicked.connect(self.plus)
        self.pushButton_2.clicked.connect(self.minus)
        self.pushButton_3.clicked.connect(self.umnozshit)
        self.pushButton_4.clicked.connect(self.delit)
        self.commandLinkButton.clicked.connect(self.link)
        self.pushButton_5.clicked.connect(self.check_form)\


    def OnClicked(self):
        if self.radioButton_2.isChecked():
            self.difficult = 'Средне'
        elif self.radioButton.isChecked():
            self.difficult = 'Легко'
        elif self.radioButton_3.isChecked():
            self.difficult = 'Сложно'

    # Функции вычисления
    def plus(self):
        str_plus = str((int(self.lineEdit.text())) + (int(self.lineEdit_2.text())))
        self.label_4.setText(str_plus)

    def minus(self):
        str_minus = str((int(self.lineEdit.text())) - (int(self.lineEdit_2.text())))
        self.label_4.setText(str_minus)

    def umnozshit(self):
        str_umn = str((int(self.lineEdit.text())) * (int(self.lineEdit_2.text())))
        self.label_4.setText(str_umn)

    def delit(self):
        str_delit = str((int(self.lineEdit.text())) / (int(self.lineEdit_2.text())))
        self.label_4.setText(str_delit)

    # Функция перехода по ссылке "Примеры"
    def link(self):
        webbrowser.open('https://logiclike.com/2.0/start?page=doshkolnik-math&intent=shkolnik')

    # Функция для отправки формы
    def check_form(self):
        if len(self.textBrowser.text()) >= 1 and self.difficult:
            self.Messege.setText(f'Привет, {self.textBrowser.text()}, ты занимался {datetime.date.today()} \nна уровне сложности "{self.difficult}".')
            self.Messege.exec_()
        else:
            self.Messege.setText('Введите Ваше имя и выберите уровень сложности!')
            self.Messege.exec_()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    win = Ui_Calcul()
    win.show()
    sys.exit(app.exec())
